# Generated by Django 4.2.25 on 2025-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_alter_customuser_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tc',
            field=models.BooleanField(default=False),
        ),
    ]
